services:
  react-ui:
    build:
      context: .
      dockerfile: ./react-ui/Dockerfile
    container_name: react-ui
    ports:
      - "3000:3000"
    volumes:
      - ./react-ui:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true
    depends_on:
      - app

  app:
    build:
      context: ./server
      dockerfile: Dockerfile 
      args:
        USE_CUDA: "false"
    container_name: app
    ports:
      - "5000:5000"
    depends_on:
      - ollama

  ollama:
    build:
      context: ./ollama
      dockerfile: Dockerfile
    container_name: ollama
    volumes:
      - ollama-data:/app/data 
    environment:
      - ENV=production
    ports:
      - "11434:11434"

volumes:
  ollama-data:
