services:
  flask-app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=${FLASK_ENV}
      - SECRET_KEY=${SECRET_KEY}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    runtime: nvidia
# react-ui:
#   build:
#     context: .
#     dockerfile: ./react-ui/Dockerfile
#   ports:
#     - "3000:3000"
#   volumes:
#     - ./react-ui:/app
#     - /app/node_modules
#   environment:
#     - NODE_ENV=development
#   stdin_open: true
#   tty: true
