version: "3.8"

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    restart: unless-stopped
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ollama-data:/root/.ollama
    ports:
      - "11434:11434"

  app:
    build:
      context: .
    container_name: emollama-app
    depends_on:
      - ollama
      - react-ui
    ports:
      - "5000:5000"
    environment:
      - OLLAMA_HOST=http://ollama:11434

  react-ui:
    build:
      context: .
      dockerfile: ./react-ui/Dockerfile
    container_name: react-ui
    ports:
      - "3000:3000"
    volumes:
      - ./react-ui:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true

volumes:
  ollama-data:
