services:
  emollama-cpu:
    build:
      context: .
      args:
        USE_CUDA: "false"
        IMAGE: python:3-slim-bookworm
    ports:
      - "5000:5000"
    container_name: emollama-cpu
    depends_on:
      - react-ui

  emollama-gpu:
    build:
      context: .
      args:
        USE_CUDA: "true"
        IMAGE: nvidia/cuda:12.5.0-devel-ubuntu22.04
    ports:
      - "5000:5000"
    container_name: emollama-gpu
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    runtime: nvidia
    depends_on:
      - react-ui

  react-ui:
    build:
      context: .
      dockerfile: ./react-ui/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./react-ui:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true